# -*- coding: utf-8 -*-
"""FAISS HW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3IiGPcGHXPtiw1wBScw3kqiMCSbIaP5
"""

# -*- coding: utf-8 -*-
"""FAISS_LABA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_sfo4_1pmvixEDyqkSGBXtehfqUKXwd
"""

!pip install --upgrade pip

!pip install faiss-cpu sentence-transformers langchain langchain-groq pandas tqdm transliterate

!pip install -U langchain-community
!pip install -U langchain

import os
import faiss
import numpy as np
import pandas as pd
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain_groq import ChatGroq
from transliterate import translit
from tqdm import tqdm

os.environ["GROQ_API_KEY"] = "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"

CSV_FILES = {
    "test": "/content/LR2_dev.csv",
    "answers": "/content/LR2_dev_answer.csv",
    "full": "/content/LR2.csv"
}
BOOKS_FOLDER = "/content/drive/MyDrive/dataset/"
OUTPUT_CSV = "/content/LR2_dev_predictions.csv"

print("✅ Все библиотеки загружены, API настроен!")

# 📜 Загружаем CSV, убирая ненужный столбец
df = pd.read_csv(CSV_FILES["full"]).drop(columns=["Unnamed: 0"], errors="ignore")

# Добавляем колонку с номерами вопросов (начиная с 1)
df.insert(0, "id", df.index)

# Переименовываем колонки
df.columns = ["id", "question", "answer_a", "answer_b", "answer_c", "answer_d", "book"]

# Выводим первые строки
print(f"📌 Колонки в файле после исправления: {df.columns.tolist()}")
print(df.head())

from google.colab import drive
import os

# Подключаем Google Drive
drive.mount('/content/drive')

import os

# 📂 Путь к папке с книгами
BOOKS_FOLDER = "/content/drive/MyDrive/dataset/"

# 📖 Словарь для хранения данных {название книги: текст}
books_data = {}

# 🔄 Рекурсивный обход всех папок и файлов
for root, dirs, files in os.walk(BOOKS_FOLDER):
    for file in files:
        if file.endswith(".txt"):  # Только текстовые файлы
            book_path = os.path.join(root, file)
            try:
                with open(book_path, "r", encoding="utf-8") as f:
                    books_data[file.replace(".txt", "")] = f.read()
            except Exception as e:
                print(f"❌ Ошибка при загрузке {book_path}: {e}")

print(f"✅ Загружено {len(books_data)} книг.")


book_name_mapping = {
    "Роковые яйца": "Bulgakov_RokovyeYayca",
    "Тарас Бульба": "Gogol_TarasBulba",
    "Мертвые души": "Gogol_MertvieDushi",
    "Дело Артамоновых": "Gorkiyi_DeloArtamonovyih",
    "Город без памяти": "Bulichev_Gorod_bez_pamyati",
    "Княгиня Лиговская": "Lermontov_KnyaginyaLigovskaya",
    "Полотенце с Петухом": "Bulgakov_PolotenceSPetuhom",
    "Звездная сыпь": "Bulgakov_ZvezdnayaSyp",
    "Стальное горло": "Bulgakov_StalnoeGorlo",
    "Вий": "Gogol_Vii",
    "Как поссорился Иван Иванович с Иваном Никифоровичем": "Gogol_KakPossorilsyaIvanIvanovichSIvanomNikiforovichem",
    "Мастер и Маргарита": "Bulgakov_MasterIMargarita",
    "Ася": "Turgenev_Asya",
    "Война и мир": "Tolstoy_VoynaIMir1",
    "Крещении поворотом": "Bulgakov_KrescheniePovorotom",
    "Сто лет тому вперёд": "Bulichev_Sto_let_tomu_vpered",
    "Муму": "Turgenev_Mumu",
    "Лиловый шар": "Bulichev_Lilovii_shar",
    "Морфий": "Bulgakov_Morfiyi",
    "Записки охотника": "Turgenev_ZapiskiOhotnika",
    "Тьма египетская": "Bulgakov_TmaEgipetskaya",
    "Приключения покойника": "Bulgakov_PriklyucheniyaPokoynika",
    "Старосветских помещиках": "Gogol_StarosvetskiyePomeshchiki",
    "Декабристы": "Tolstoy_Decabristy",
    "Человек-амфибия": "Belyaev_CheloverAmfibia",
    "Чертова мельница": "Belyaev_ChyortovaMelnica",
    "Голова профессора Доуэля": "Belyaev_GolovaProfessoraDouyelya",
    "Над бездной": "Belyaev_NadBezdnoyi",
    "Невидимый свет": "Belyaev_NevidimyiyiSvet",
    "Ни жизнь, ни смерть": "Belyaev_NiJiznNiSmert",
    "Продавец воздуха": "Belyaev_ProdavecVozduhaI",
    "Пропавший остров": "Belyaev_PropavshiyiOstrov",
    "Сильнее бога": "Belyaev_SilneeBoga",
    "Верхом на ветре": "Belyaev_VerhomNaVetre",
    "Властелин мира": "Belyaev_VlastelinMira",
    "Золотая гора": "Belyaev_ZolotayaGora",
    "Бесы": "Dostoevskiyi_BesyiII",
    "Братья Карамазовы": "Dostoevskiyi_BratyaKaramazovyi",
    "Идиот": "Dostoevskiyi_Idiot",
    "Преступление и наказание": "Dostoevskiyi_PrestuplenieINakazanie",
    "Сборник": "Gogol_Sbornik",
    "Детство": "Gorkiyi_Detstvo",
    "Жизнь Клима Самгина": "Gorkiyi_JiznKlimaSamgina",
    "Старуха Изергиль": "Gorkiyi_StaruhaIzergil",
    "В людях": "Gorkiyi_VLyudyah",
    "Детство. В людях. Мои университеты": "Gorkiyi_YeksklyuzivrusDetstvoVLyudyahMoiUni",
    "Гранатовый браслет": "Kuprin_GranatovyiyiBraslet",
    "Добрый доктор": "Kuprin_HrestomatiidlyDobryiyiDoktor",
    "Олеся": "Kuprin_Olesya",
    "Поединок": "Kuprin_Poedinok",
    "Суламифь": "Kuprin_Sulamif",
    "Яма": "Kuprin_Yama",
    "Ашик-Кериб": "Lermontov_AshikKerib",
    "Герой нашего времени": "Lermontov_GeroyiNashegoVremeni",
    "Хрестоматия для Ашик-Кериб": "Lermontov_HrestomatiidlyAshikKerib",
    "Книягиня Лиговская": "Lermontov_KnyaginyaLigovskaya",
    "Штосс": "Lermontov_Shtoss",
    "Богач и Еремка": "MaminSibiryak_BogachIEremka",
    "Емеля-охотник": "MaminSibiryak_EmelyaOhotnik",
    "Горное гнездо": "MaminSibiryak_GornoeGnezdo",
    "Постойко": "MaminSibiryak_Postoyiko",
    "Приёмыш": "MaminSibiryak_Priemyish",
    "Приваловские миллионы": "MaminSibiryak_PrivalovskieMillionyi",
    "Серая шейка": "MaminSibiryak_SerayaSheyika",
    "Вертел": "MaminSibiryak_Vertel",
    "В глуши": "MaminSibiryak_VGlushiI",
    "Золото": "MaminSibiryak_Zoloto",
    "Апеллесова черта": "Pasternak_ApellesovaCherta",
    "Доктор Живаго": "Pasternak_DoktorZhivago",
    "Судьба человека": "Sholohov_SudbaCheloveka",
    "Поднятая целина": "Sholokhov_PodnyatayaTselina",
    "Тихий Дон": "Sholokhov_TikhiyDon",
    "Детство": "Tolstoy_Detstvo",
    "Отрочество": "Tolstoy_Otrochestvo",
    "Семейное счастье": "Tolstoy_SemeynoyeSchastye",
    "Воскресенье": "Tolstoy_Voskreseniye",
    "Война и Мир 1": "Tolstoy_VoynaIMir1",
    "Война и Мир 2": "Tolstoy_VoynaIMir2",
    "Юность": "Tolstoy_Yunost",
    "Ася": "Turgenev_Asya",
    "Дворянское гнездо": "Turgenev_DvoryanskoeGnezdo",
    "Муму": "Turgenev_Mumu",
    "Накануне": "Turgenev_Nakanune",
    "Отцы и дети": "Turgenev_OtcyiIDeti",
    "Первая любовь": "Turgenev_PervayaLyubov",
    "Записки охотника": "Turgenev_ZapiskiOhotnika"

}

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from tqdm import tqdm

# 🔧 Разбиваем книги на фрагменты
splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)

# 🔑 Используем модель для создания векторных представлений
embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
    model_kwargs={"device": "cuda"}  # Используем CPU
)

# Словарь для хранения FAISS хранилищ
vector_stores = {}

# Создание векторных хранилищ
for book_name, text in tqdm(books_data.items(), desc="Создание векторных хранилищ", unit="книга"):
    # Разбиваем текст на фрагменты
    split_documents = splitter.create_documents([text])

    # Создаем векторное хранилище для каждого произведения
    vector_store = FAISS.from_documents(split_documents, embedding_model)

    # Сохраняем векторное хранилище
    vector_stores[book_name] = vector_store

print(f"✅ Векторные хранилища созданы для {len(vector_stores)} книг.")

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_groq import ChatGroq
import random

# ⚡ Подключаем LLM
llm = ChatGroq(model_name="llama3-70b-8192")

# 💬 Шаблон промпта для LLM
prompt = PromptTemplate.from_template("""
Используя приведенный контекст из книги, выбери правильный ответ на вопрос.
Выбери **ТОЛЬКО ОДНУ БУКВУ** (A, B, C или D), без пояснений.

Контекст:
{context}

Вопрос:
{question}

A) {option_a}
B) {option_b}
C) {option_c}
D) {option_d}

Ответ:  """)

# 🔗 Создаем цепочку для LLM
chain = LLMChain(prompt=prompt, llm=llm)

# 🔄 Преобразуем A, B, C, D → 1, 2, 3, 4
answer_map = {"A": 1, "B": 2, "C": 3, "D": 4}

# 🏆 Функция поиска правильного ответа
def find_correct_answer(question_index):
    row = df.iloc[question_index]  # Берем строку по индексу

    original_book_name = row["book"].strip()  # Оригинальное название из CSV
    book_name = book_name_mapping.get(original_book_name, None)  # Ищем в словаре

    if not book_name:
        print(f"⚠️ Книга '{original_book_name}' не найдена в словаре! Пропускаем...")
        return -1  # Если книги нет в словаре, возвращаем -1

    query = row["question"]

    # 🔎 Ищем ответ в книге
    if book_name in vector_stores:
        context_docs = vector_stores[book_name].similarity_search(query, k=3)
        context = "\n\n".join([doc.page_content for doc in context_docs])
    else:
        context = "Контекст не найден."

    # print(f"📖 Контекст для вопроса {question_index}:\n{context}")

    # 🧠 Запускаем LLM для поиска ответа
    result = chain.invoke({
        "context": context,
        "question": query,
        "option_a": row["answer_a"],
        "option_b": row["answer_b"],
        "option_c": row["answer_c"],
        "option_d": row["answer_d"]
    })
    # print(f"🔍 Ответ от LLM: {result}")

    if isinstance(result, dict):
        result = result.get("text", "").strip().upper()

    # 🎯 Оставляем только первую букву ответа
    result = result[:1] if result and result[0] in "ABCD" else "A"

    print(f"✅ Итоговый ответ: {result}")
    return answer_map.get(result, 1)  # Если ответ невалидный, возвращаем -1


# 🚀 Запускаем обработку всех вопросов
results = []
for question_index in range(len(df)):  # Идем по индексам
    correct_answer = find_correct_answer(question_index)
    results.append({"id": question_index, "answer": correct_answer})
    print(f"✅ Вопрос {question_index}: Ответ {correct_answer}")

# 💾 Сохраняем результаты в CSV
output_csv = "/content/LR2_predictions.csv"
results_df = pd.DataFrame(results)
results_df.to_csv(output_csv, index=False)

print(f"🎯 Файл с ответами сохранен: {output_csv}")

# проверяем, какие книги у нас есть
print("📚 Книги в vector_stores:", list(vector_stores.keys()))
print("📚 Уникальные названия в CSV:", df["book"].unique())